saturio_opcache_reset:
    path: /opcache/reset
    controller: Saturio\OpcacheManagerBundle\Controller\ResetController::reset

saturio_get_status:
    path: /opcache/status
    controller: Saturio\OpcacheManagerBundle\Controller\StatusController::getStatus

saturio_get_configuration:
    path: /opcache/configuration
    controller: Saturio\OpcacheManagerBundle\Controller\ConfigurationController::getConfiguration
