name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  phpunit:

    runs-on: ubuntu-latest
    env:
      SYMFONY_REQUIRE: ${{matrix.symfony-require}}
      SYMFONY_DEPRECATIONS_HELPER: ${{matrix.symfony-deprecations-helper}}

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.4"
          - "8.0"
        dependencies:
          - "highest"
        stability:
          - "stable"
        symfony-require:
          - ""
        symfony-deprecations-helper:
          - ""
        include:
          # Tests the lowest set of dependencies
          - dependencies: "lowest"
            stability: "stable"
            php-version: "7.4"
            symfony-deprecations-helper: "weak"

          # Test against latest Symfony 4.4
          - symfony-require: "4.4.*"
            dependencies: "highest"
            php-version: "7.4"
            symfony-deprecations-helper: "weak"

          # Test against latest Symfony 5 dev
          - symfony-require: "5.*"
            dependencies: "highest"
            php-version: "7.4"
            symfony-deprecations-helper: "weak"

          - php-version: "8.0"
            dependencies: "highest"
            stability: "dev"
            symfony-deprecations-helper: "weak"

    steps:
    - uses: actions/checkout@v2

    - name: "Install PHP"
      uses: "shivammathur/setup-php@v2"
      with:
        coverage: "none"
        php-version: "${{ matrix.php-version }}"

    - name: Display versions
      run: |
          php -r 'foreach (get_loaded_extensions() as $extension) echo $extension . " " . phpversion($extension) . PHP_EOL;'
          php -i

    - name: "Globally install symfony/flex"
      run: "composer global require --no-progress --no-scripts --no-plugins symfony/flex"

    - name: "Enforce using stable dependencies"
      run: "composer config minimum-stability stable"
      if: "${{ matrix.stability == 'stable' }}"

    - name: "Install dependencies with Composer"
      uses: "ramsey/composer-install@v1"
      with:
        dependency-versions: "${{ matrix.dependencies }}"
        composer-options: "--prefer-dist"

    - name: "Run PHPUnit"
      run: "vendor/bin/simple-phpunit --coverage-clover=coverage.xml"
